//! DrawList — unified geometry representation consumed by all renderers.
//!
//! ALL visual elements are pre-computed into pixel-space primitives by
//! GeometryGenerator. Renderers are "dumb" — they just draw these primitives.
//! This guarantees pixel-perfect consistency between Canvas2D and WebGPU.

use bytemuck::{Pod, Zeroable};

/// A filled rectangle in physical pixel coordinates.
/// This is the GPU instance struct — bytemuck-compatible for direct upload.
#[repr(C)]
#[derive(Debug, Clone, Copy, Pod, Zeroable)]
pub struct ColoredRect {
    /// Left edge X in physical pixels.
    pub x: f32,
    /// Top edge Y in physical pixels.
    pub y: f32,
    /// Width in physical pixels.
    pub w: f32,
    /// Height in physical pixels.
    pub h: f32,
    /// RGBA color (0.0–1.0).
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
}

/// A line segment in physical pixel coordinates (for future studies/drawings).
#[derive(Debug, Clone, Copy)]
pub struct ColoredLine {
    pub x0: f32,
    pub y0: f32,
    pub x1: f32,
    pub y1: f32,
    pub width: f32,
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
    /// Dash pattern: [dash_len, gap_len]. Both 0.0 = solid.
    pub dash: f32,
    pub gap: f32,
}

/// Text element in physical pixel coordinates (for future overlay on main canvas).
#[derive(Debug, Clone)]
pub struct DrawText {
    pub text: String,
    pub x: f32,
    pub y: f32,
    pub font_size: f32,
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub a: f32,
}

/// The complete draw list for one frame. Generated by GeometryGenerator,
/// consumed identically by Canvas2D and WebGPU renderers.
#[derive(Debug, Clone)]
pub struct DrawList {
    /// Filled rectangles (candle bodies, wicks, borders, volume bars).
    pub rects: Vec<ColoredRect>,
    /// Line segments (for future studies/drawings).
    pub lines: Vec<ColoredLine>,
    /// Text elements (for future main-canvas text).
    pub texts: Vec<DrawText>,
}

impl DrawList {
    pub fn new() -> Self {
        Self {
            rects: Vec::with_capacity(4096),
            lines: Vec::with_capacity(256),
            texts: Vec::with_capacity(64),
        }
    }

    pub fn clear(&mut self) {
        self.rects.clear();
        self.lines.clear();
        self.texts.clear();
    }
}
