/**
 * @aion/charts — public API (snake_case; semantics mirror lightweight-charts v5).
 *
 * A thin, typed façade over the `aion_wasm` engine. It owns the browser-side concerns that the
 * engine deliberately leaves out: creating the two stacked canvases (WebGPU/Canvas2D pane +
 * Canvas2D axis overlay), the input-gesture recognizer, typed-array packing of data at the
 * boundary, and the chart/series/time-scale handle objects. All model, layout, and rendering math
 * lives in Rust.
 *
 * WebGPU device acquisition is async, so `create_chart` returns a Promise — the one deliberate
 * divergence from LWC's synchronous `createChart`.
 */

// The wasm glue is generated by `wasm-pack` into ../pkg (see `npm run build:wasm`). esbuild inlines
// it when bundling; the .wasm is fetched at runtime relative to the output bundle.
// @ts-ignore -- pkg is a build artifact, present after build:wasm
import init, { create_chart as wasm_create_chart, AionChart } from "../pkg/aion_wasm.js";

// ---------------------------------------------------------------------------------------------
// Data & option types
// ---------------------------------------------------------------------------------------------

/** A series kind. Maps to the engine's numeric kind at the boundary. */
export type series_kind = "candlestick" | "bar" | "line" | "area" | "histogram" | "baseline";

/** OHLC bar for candlestick/bar series. `time` is UTC seconds. */
export interface ohlc_data {
  time: number;
  open: number;
  high: number;
  low: number;
  close: number;
}

/** Single-value point for line/area/histogram series. `time` is UTC seconds. */
export interface single_value_data {
  time: number;
  value: number;
}

export type series_data = ohlc_data | single_value_data;

/** Inclusive logical (bar-index) range. */
export interface logical_range {
  from: number;
  to: number;
}

/** Inclusive time range (UTC seconds). */
export interface time_range {
  from: number;
  to: number;
}

export interface bars_info extends Partial<time_range> {
  bars_before: number;
  bars_after: number;
}

/** LWC mismatch-direction values used by `data_by_index`. */
export type mismatch_direction = -1 | 0 | 1;
export type data_changed_scope = "full" | "update";
export type data_changed_handler = (scope: data_changed_scope) => void;

/** Parameters delivered to crosshair-move and click subscribers (mirrors LWC `MouseEventParams`). */
export interface mouse_event_params {
  /** UTC seconds of the bar under the cursor, or `null` off the data. */
  time: number | null;
  /** Float logical (bar) index under the cursor, or `null` when there is no data. */
  logical: number | null;
  /** Cursor position in CSS px relative to the pane, or `null` when the cursor left the chart. */
  point: { x: number; y: number } | null;
  /** Per-series value at the hovered bar, keyed by the series handle. */
  series_data: Map<series_api, ohlc_data | single_value_data>;
}

export type mouse_event_handler = (params: mouse_event_params) => void;
export type dbl_click_handler = (params: mouse_event_params) => void;
export type visible_logical_range_handler = (range: logical_range | null) => void;
export type visible_time_range_handler = (range: time_range | null) => void;

export interface time_scale_options {
  /** Distance between adjacent bars in CSS pixels. */
  bar_spacing: number;
  /** Empty logical bars between the final data point and the right edge. */
  right_offset: number;
}

export interface price_scale_options {
  /** 0 normal, 1 logarithmic, 2 percentage, 3 indexed-to-100 (LWC values). */
  mode: 0 | 1 | 2 | 3;
  auto_scale: boolean;
  invert_scale: boolean;
  scale_margins: { top: number; bottom: number };
}

/** The visible raw-value range of a price scale. */
export interface price_range {
  from: number;
  to: number;
}

/** Deeply-partial chart options; forwarded to the engine and deep-merged there (LWC semantics). */
export type deep_partial<T> = { [K in keyof T]?: deep_partial<T[K]> };

export interface grid_line_options {
  color: string;
  style: number;
  visible: boolean;
}
export interface chart_options {
  layout: { background: { type: string; color: string }; textColor: string; fontSize: number; fontFamily: string; attributionLogo: boolean };
  grid: { vertLines: grid_line_options; horzLines: grid_line_options };
  crosshair: { vertLine: Partial<grid_line_options>; horzLine: Partial<grid_line_options>; mode: number };
  leftPriceScale: { visible: boolean };
  rightPriceScale: { visible: boolean };
  /** Install a ResizeObserver so the chart tracks its container's size. Default `false` (LWC parity). */
  autoSize: boolean;
  hoveredSeriesOnTop: boolean;
  /** Backend override for capability testing; defaults to automatic WebGPU → Canvas2D fallback. */
  backend: "auto" | "canvas2d";
}

/** Options accepted when adding a series. */
export interface series_options {
  /** Overrides the kind default color (line/area/histogram). */
  color: string;
  /** Candlestick/bar up (close ≥ open) body color. Any CSS color the engine parses. */
  up_color: string;
  /** Candlestick/bar down (close < open) body color. */
  down_color: string;
  /** Line/area stroke width in css px (default 3). */
  line_width: number;
  /** Area fill color at the line (top of the gradient). */
  area_top_color: string;
  /** Area fill color at the base (bottom of the gradient; usually fully transparent). */
  area_bottom_color: string;
  /**
   * Histogram only: color each bar by the main price series' up/down direction at that time
   * (translucent green/red), matching TradingView-style volume. Default false (solid `color`).
   */
  histogram_updown: boolean;
  /**
   * Place the series on the bottom-band overlay price scale (volume-style): its magnitude is
   * excluded from the main price axis autoscale. Mirrors LWC's `priceScaleId: ''` + scaleMargins.
   */
  overlay: boolean;
  /** LWC price-scale id: visible left/right pane axis, or empty string for an overlay scale. */
  price_scale_id: "left" | "right" | "";
  /** Camel-case LWC alias of `price_scale_id`. */
  priceScaleId: "left" | "right" | "";
  /** Overlay band as fractions of pane height (default `{ top: 0.8, bottom: 0 }` ⇒ bottom fifth). */
  scale_margins: { top: number; bottom: number };
  /** Stacked pane index (0 = top/price pane). A new pane is created on demand (roadmap Phase B1). */
  pane: number;
  /** Relative height of a newly-created pane (default 1; the price pane is 3). */
  pane_stretch: number;
  /** Line/area join type (roadmap Phase B3). */
  line_type: "simple" | "stepped" | "curved";
  /** Draw a disc at each data point (shown when bars are spaced enough), roadmap Phase B3. */
  point_markers: boolean;
  /** Baseline price for a baseline series (omit for auto = visible-range midpoint). */
  baseline_value: number;
  /** Pulse an expanding ring at the last value (drives an rAF loop), roadmap Phase B3. */
  last_price_animation: boolean;
  /** Keep the series in the engine while toggling its visibility. */
  visible: boolean;
}

const LINE_TYPE_TO_U8: Record<NonNullable<series_options["line_type"]>, number> = {
  simple: 0,
  stepped: 1,
  curved: 2,
};

/** Style of a price line / crosshair line. */
export type line_style = "solid" | "dotted" | "dashed" | "large_dashed" | "sparse_dotted";
const LINE_STYLE_TO_U8: Record<line_style, number> = {
  solid: 0,
  dotted: 1,
  dashed: 2,
  large_dashed: 3,
  sparse_dotted: 4,
};

/** Options for {@link series_api.create_price_line}. */
export interface price_line_options {
  price: number;
  color?: string;
  line_width?: number;
  line_style?: line_style;
  /** Axis label text; defaults to the formatted price. */
  title?: string;
}

/** A handle to a created price line. */
export interface price_line_api {
  remove(): void;
  readonly id: number;
}

/** A per-bar marker on a series (roadmap Phase B4). Mirrors lightweight-charts `SeriesMarker`. */
export interface series_marker {
  /** Bar time (must match a data point's time). */
  time: number;
  /** Placement relative to the bar. LWC names are canonical; short aliases remain compatible. */
  position?: "aboveBar" | "belowBar" | "inBar" | "above" | "below";
  /** Marker shape. Default `"circle"`. */
  shape?: "circle" | "square" | "arrowUp" | "arrowDown";
  /** Fill color (any CSS color the engine parses). Default series color. */
  color?: string;
  /** Optional label rendered beside the marker. */
  text?: string;
}

export interface series_marker_options {
  /** Expand price-scale pixel margins so marker shapes remain visible. Default `true` (LWC). */
  auto_scale: boolean;
}

const KIND_TO_U8: Record<series_kind, number> = {
  candlestick: 0,
  bar: 1,
  line: 2,
  area: 3,
  histogram: 4,
  baseline: 5,
};

// ---------------------------------------------------------------------------------------------
// Handles
// ---------------------------------------------------------------------------------------------

/** A single data series on the chart. */
export interface series_api {
  /** Replace the series' data. Accepts OHLC or single-value points; packed to typed arrays here. */
  set_data(data: readonly series_data[]): void;
  /** Append a new point or replace the last one (streaming). */
  update(point: series_data): void;
  /** Apply series options (currently: `color`). */
  apply_options(options: Partial<series_options>): void;
  /** Change how the primary series is drawn (candlestick/bar/line/area/histogram). */
  set_type(kind: series_kind): void;
  /** Move this series into stacked pane `pane_index` (0 = price pane), creating it if needed. */
  move_to_pane(pane_index: number, stretch?: number): void;
  /** Add a horizontal price line on this series; returns a handle with `.remove()`. */
  create_price_line(options: price_line_options): price_line_api;
  /** Replace this series' per-bar markers (pass `[]` to clear). Roadmap Phase B4. */
  set_markers(markers: readonly series_marker[], options?: Partial<series_marker_options>): void;
  /** Price-scale handle currently used by this series. */
  price_scale(): price_scale_api;
  price_to_coordinate(price: number): number | null;
  coordinate_to_price(coordinate: number): number | null;
  bars_in_logical_range(range: logical_range): bars_info | null;
  data_by_index(logical_index: number, mismatch_direction?: mismatch_direction): series_data | null;
  data(): readonly series_data[];
  series_type(): series_kind;
  subscribe_data_changed(handler: data_changed_handler): void;
  unsubscribe_data_changed(handler: data_changed_handler): void;
  /** The engine-side series id. */
  readonly id: number;
}

/** The horizontal (time) scale. */
export interface time_scale_api {
  /** Distance in logical bars between the latest point and the right edge. */
  scroll_position(): number;
  /** Scroll to a logical right-edge position. Animation is currently applied immediately. */
  scroll_to_position(position: number, animated: boolean): void;
  /** Return the latest point to the real-time edge. */
  scroll_to_real_time(): void;
  /** Restore configured default spacing and right offset. */
  reset_time_scale(): void;
  fit_content(): void;
  apply_options(options: Partial<time_scale_options>): void;
  options(): time_scale_options;
  get_visible_logical_range(): logical_range | null;
  set_visible_logical_range(range: logical_range): void;
  get_visible_range(): time_range | null;
  set_visible_range(range: time_range): void;
  /** Fire after the visible logical range changes. */
  subscribe_visible_logical_range_change(handler: visible_logical_range_handler): void;
  unsubscribe_visible_logical_range_change(handler: visible_logical_range_handler): void;
  /** Fire after the visible time range changes. */
  subscribe_visible_time_range_change(handler: visible_time_range_handler): void;
  unsubscribe_visible_time_range_change(handler: visible_time_range_handler): void;
  time_to_coordinate(time: number): number | null;
  coordinate_to_time(x: number): number | null;
  logical_to_coordinate(logical: number): number | null;
  coordinate_to_logical(x: number): number | null;
  /** Exact timestamp lookup, or LWC-compatible lower-bound lookup when `find_nearest` is true. */
  time_to_index(time: number, find_nearest?: boolean): number | null;
  /** Current media-coordinate width of the horizontal scale. */
  width(): number;
  /** Current media-coordinate height of the horizontal axis, or zero when hidden. */
  height(): number;
}

/** A pane price scale. Left/right are visible axes; the empty id is an independent overlay. */
export interface price_scale_api {
  apply_options(options: deep_partial<price_scale_options>): void;
  options(): price_scale_options;
  width(): number;
  set_visible_range(range: price_range): void;
  get_visible_range(): price_range | null;
  set_auto_scale(on: boolean): void;
}

/** The chart. Create with {@link create_chart}. */
/** A stacked pane (roadmap Phase B1). Mirrors lightweight-charts `IPaneApi`. */
export interface pane_api {
  /** This pane's index (0 = top/price pane). */
  pane_index(): number;
  /** Current CSS height in px (from the last layout pass). */
  get_height(): number;
  /** Resize this pane to `height` CSS px, absorbing the delta from its neighbour. */
  set_height(height: number): void;
  /** This pane's relative stretch factor (height weight). */
  get_stretch_factor(): number;
  /** Set this pane's relative stretch factor. */
  set_stretch_factor(factor: number): void;
}

export interface chart_api {
  /** Active pane backend: `webgpu` when available, otherwise the shared `canvas2d` fallback. */
  backend(): "webgpu" | "canvas2d";
  add_series(kind: series_kind, options?: Partial<series_options>): series_api;
  /** Add a Rust-native simple moving-average line derived from an existing series. */
  add_sma(source: series_api, period: number, options?: Partial<series_options>): series_api;
  /** Add a Rust-native exponential moving-average line derived from an existing series. */
  add_ema(source: series_api, period: number, options?: Partial<series_options>): series_api;
  /** Add upper, middle, and lower Rust-native Bollinger-band lines. */
  add_bollinger(source: series_api, period: number, deviation?: number, options?: Partial<series_options>): [series_api, series_api, series_api];
  apply_options(options: deep_partial<chart_options>): void;
  options(): unknown;
  time_scale(): time_scale_api;
  price_scale(price_scale_id?: "left" | "right" | "", pane_index?: number): price_scale_api;
  /** The stacked panes, top to bottom (roadmap Phase B1). At least one always exists. */
  panes(): pane_api[];
  price_to_coordinate(price: number): number | null;
  coordinate_to_price(y: number): number | null;
  /** Fire on every crosshair move (and once with `point: null` when the cursor leaves). */
  subscribe_crosshair_move(handler: mouse_event_handler): void;
  unsubscribe_crosshair_move(handler: mouse_event_handler): void;
  /** Fire on a click/tap inside the pane. */
  subscribe_click(handler: mouse_event_handler): void;
  unsubscribe_click(handler: mouse_event_handler): void;
  /** Fire on a double-click inside the pane (the default fit-content action still runs). */
  subscribe_dbl_click(handler: dbl_click_handler): void;
  unsubscribe_dbl_click(handler: dbl_click_handler): void;
  /** Fire after the visible logical range changes. */
  subscribe_visible_logical_range_change(handler: visible_logical_range_handler): void;
  unsubscribe_visible_logical_range_change(handler: visible_logical_range_handler): void;
  /** Fire after the visible time range changes. */
  subscribe_visible_time_range_change(handler: visible_time_range_handler): void;
  unsubscribe_visible_time_range_change(handler: visible_time_range_handler): void;
  /** Manually set the CSS size (and optional devicePixelRatio). Ignored while `autoSize` is on. */
  resize(width: number, height: number, dpr?: number): void;
  /** Force a repaint. Normally unnecessary — mutating calls repaint themselves. */
  render(): void;
  /** Snapshot the composed pane and axis layers at their current device-pixel resolution. */
  take_screenshot(): HTMLCanvasElement;
  /** Tear down: remove canvases and listeners. */
  remove(): void;
}

// ---------------------------------------------------------------------------------------------
// Implementation
// ---------------------------------------------------------------------------------------------

let init_promise: Promise<unknown> | null = null;
/** Instantiate the wasm module once per page. */
function ensure_init(): Promise<unknown> {
  if (init_promise === null) {
    init_promise = init();
  }
  return init_promise;
}

function undef_to_null<T>(v: T | undefined): T | null {
  return v === undefined ? null : v;
}

function same_logical_range(a: logical_range | null, b: logical_range | null): boolean {
  return a === b || (a !== null && b !== null && a.from === b.from && a.to === b.to);
}

function same_time_range(a: time_range | null, b: time_range | null): boolean {
  return a === b || (a !== null && b !== null && a.from === b.from && a.to === b.to);
}

/** Pack a data array into the six Float64Arrays the engine expects (single-value → o=h=l=c). */
function pack(data: readonly series_data[]): {
  times: Float64Array;
  open: Float64Array;
  high: Float64Array;
  low: Float64Array;
  close: Float64Array;
} {
  const n = data.length;
  const times = new Float64Array(n);
  const open = new Float64Array(n);
  const high = new Float64Array(n);
  const low = new Float64Array(n);
  const close = new Float64Array(n);
  for (let i = 0; i < n; i++) {
    const d = data[i] as series_data;
    times[i] = d.time;
    if ("value" in d) {
      open[i] = high[i] = low[i] = close[i] = d.value;
    } else {
      open[i] = d.open;
      high[i] = d.high;
      low[i] = d.low;
      close[i] = d.close;
    }
  }
  return { times, open, high, low, close };
}

/** Parse a CSS hex or rgb()/rgba() color to 8-bit channels (mirrors the Rust `Color::parse_css`). */
function parse_rgb(css: string): [number, number, number] | null {
  const s = css.trim();
  if (s.startsWith("#")) {
    const h = s.slice(1);
    const expand = (c: string) => parseInt(c + c, 16);
    if (h.length === 3 || h.length === 4) {
      return [expand(h[0]!), expand(h[1]!), expand(h[2]!)];
    }
    if (h.length === 6 || h.length === 8) {
      return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
    }
    return null;
  }
  const m = s.match(/^rgba?\(([^)]+)\)$/i);
  if (m) {
    const parts = m[1]!.split(",").map((p) => parseFloat(p.trim()));
    if (parts.length >= 3 && parts.every((p) => !Number.isNaN(p))) {
      return [Math.round(parts[0]!), Math.round(parts[1]!), Math.round(parts[2]!)];
    }
  }
  return null;
}

class series_impl implements series_api {
  private readonly data_changed_subs = new Set<data_changed_handler>();

  constructor(
    readonly id: number,
    readonly kind: series_kind,
    private readonly chart: chart_impl,
  ) {}

  set_data(data: readonly series_data[]): void {
    const p = pack(data);
    this.chart.wasm.set_series_data_typed(this.id, p.times, p.open, p.high, p.low, p.close);
    this.chart.repaint();
    for (const handler of this.data_changed_subs) handler("full");
  }

  update(point: series_data): void {
    const o = "value" in point ? point.value : point.open;
    const h = "value" in point ? point.value : point.high;
    const l = "value" in point ? point.value : point.low;
    const c = "value" in point ? point.value : point.close;
    // Series-scoped streaming: append a new time point or replace the last on this series.
    this.chart.wasm.update_series_bar(this.id, point.time, o, h, l, c);
    this.chart.repaint();
    for (const handler of this.data_changed_subs) handler("update");
  }

  apply_options(options: Partial<series_options>): void {
    if (options.color !== undefined) {
      const rgb = parse_rgb(options.color);
      if (rgb) {
        this.chart.wasm.set_series_color(this.id, rgb[0], rgb[1], rgb[2]);
      }
    }
    if (options.visible !== undefined) {
      this.chart.wasm.set_series_visible(this.id, options.visible);
    }
    if (options.up_color !== undefined || options.down_color !== undefined) {
      // CSS strings passed through so the engine keeps alpha; empty = leave unchanged.
      this.chart.wasm.set_series_updown_colors(this.id, options.up_color ?? "", options.down_color ?? "");
    }
    if (options.line_width !== undefined) {
      this.chart.wasm.set_series_line_width(this.id, options.line_width);
    }
    if (options.area_top_color !== undefined || options.area_bottom_color !== undefined) {
      this.chart.wasm.set_series_area_colors(this.id, options.area_top_color ?? "", options.area_bottom_color ?? "");
    }
    if (options.histogram_updown !== undefined) {
      this.chart.wasm.set_series_histogram_updown(this.id, options.histogram_updown);
    }
    if (options.pane !== undefined && options.pane > 0) {
      this.chart.wasm.set_series_pane(this.id, options.pane, options.pane_stretch ?? 1);
    }
    if (options.line_type !== undefined) {
      this.chart.wasm.set_series_line_type(this.id, LINE_TYPE_TO_U8[options.line_type]);
    }
    if (options.point_markers !== undefined) {
      this.chart.wasm.set_series_point_markers(this.id, options.point_markers);
    }
    if (options.baseline_value !== undefined) {
      this.chart.wasm.set_series_baseline(this.id, options.baseline_value);
    }
    if (options.overlay) {
      const m = options.scale_margins ?? { top: 0.8, bottom: 0 };
      this.chart.wasm.set_series_overlay(this.id, m.top, m.bottom);
    } else if (options.price_scale_id !== undefined || options.priceScaleId !== undefined) {
      const id = options.priceScaleId ?? options.price_scale_id;
      const target = id === "left" ? 1 : id === "" ? 2 : 0;
      this.chart.wasm.set_series_price_scale(this.id, target);
      if (target === 2) {
        const m = options.scale_margins ?? { top: 0.8, bottom: 0 };
        this.chart.wasm.set_series_overlay(this.id, m.top, m.bottom);
      }
    }
    if (options.last_price_animation !== undefined) {
      this.chart.wasm.set_series_last_price_animation(this.id, options.last_price_animation);
      this.chart.sync_animation();
    }
    this.chart.repaint();
  }

  set_type(kind: series_kind): void {
    if (this.id === 0) {
      this.chart.wasm.set_series_type(KIND_TO_U8[kind]);
    } else {
      console.warn("aion: set_type() currently supports the primary series only");
    }
    this.chart.repaint();
  }

  move_to_pane(pane_index: number, stretch = 1): void {
    this.chart.wasm.set_series_pane(this.id, pane_index, stretch);
    this.chart.repaint();
  }

  create_price_line(options: price_line_options): price_line_api {
    const rgb = parse_rgb(options.color ?? "#2196f3") ?? [0x21, 0x96, 0xf3];
    const style = LINE_STYLE_TO_U8[options.line_style ?? "solid"];
    const id = this.chart.wasm.create_price_line(
      this.id,
      options.price,
      rgb[0],
      rgb[1],
      rgb[2],
      options.line_width ?? 1,
      style,
      options.title ?? "",
    );
    this.chart.repaint();
    const chart = this.chart;
    return {
      id,
      remove() {
        chart.wasm.remove_price_line(id);
        chart.repaint();
      },
    };
  }

  set_markers(markers: readonly series_marker[], options?: Partial<series_marker_options>): void {
    if (options?.auto_scale !== undefined) {
      this.chart.wasm.set_series_markers_auto_scale(this.id, options.auto_scale);
    }
    this.chart.wasm.set_series_markers(this.id, JSON.stringify(markers));
    this.chart.repaint();
  }

  price_scale(): price_scale_api {
    const pane = undef_to_null(this.chart.wasm.series_pane_index(this.id)) ?? 0;
    const target = undef_to_null(this.chart.wasm.series_price_scale_id(this.id)) ?? 0;
    return new price_scale_impl(this.chart, pane, target);
  }
  price_to_coordinate(price: number): number | null {
    return undef_to_null(this.chart.wasm.series_price_to_coordinate(this.id, price));
  }
  coordinate_to_price(coordinate: number): number | null {
    return undef_to_null(this.chart.wasm.series_coordinate_to_price(this.id, coordinate));
  }
  bars_in_logical_range(range: logical_range): bars_info | null {
    const info = this.chart.wasm.series_bars_in_logical_range(this.id, range.from, range.to);
    if (info.length < 2) return null;
    return info.length === 4
      ? { bars_before: info[0]!, bars_after: info[1]!, from: info[2]!, to: info[3]! }
      : { bars_before: info[0]!, bars_after: info[1]! };
  }
  private unpack_point(values: Float64Array | number[], offset = 0): series_data | null {
    if (values.length < offset + 5) return null;
    const time = values[offset]!;
    if (this.series_type() === "candlestick" || this.series_type() === "bar") {
      return {
        time,
        open: values[offset + 1]!,
        high: values[offset + 2]!,
        low: values[offset + 3]!,
        close: values[offset + 4]!,
      };
    }
    return { time, value: values[offset + 4]! };
  }
  data_by_index(logical_index: number, mismatch_direction: mismatch_direction = 0): series_data | null {
    return this.unpack_point(
      this.chart.wasm.series_data_by_index(this.id, logical_index, mismatch_direction),
    );
  }
  data(): readonly series_data[] {
    const values = this.chart.wasm.series_data(this.id);
    const output: series_data[] = [];
    for (let offset = 0; offset + 4 < values.length; offset += 5) {
      const point = this.unpack_point(values, offset);
      if (point !== null) output.push(point);
    }
    return output;
  }
  series_type(): series_kind {
    const kind = this.chart.wasm.series_kind(this.id) ?? KIND_TO_U8[this.kind];
    return (["candlestick", "bar", "line", "area", "histogram", "baseline"] as const)[kind]
      ?? "candlestick";
  }
  subscribe_data_changed(handler: data_changed_handler): void {
    this.data_changed_subs.add(handler);
  }
  unsubscribe_data_changed(handler: data_changed_handler): void {
    this.data_changed_subs.delete(handler);
  }
}

class time_scale_impl implements time_scale_api {
  constructor(private readonly chart: chart_impl) {}

  scroll_position(): number {
    return this.chart.wasm.scroll_position();
  }
  scroll_to_position(position: number, _animated: boolean): void {
    this.chart.wasm.scroll_to_position(position);
    this.chart.repaint();
  }
  scroll_to_real_time(): void {
    this.chart.wasm.scroll_to_real_time();
    this.chart.repaint();
  }
  reset_time_scale(): void {
    this.chart.wasm.reset_time_scale();
    this.chart.repaint();
  }
  fit_content(): void {
    this.chart.wasm.fit_content();
    this.chart.repaint();
  }
  apply_options(options: Partial<time_scale_options>): void {
    if (options.bar_spacing !== undefined) this.chart.wasm.set_bar_spacing(options.bar_spacing);
    if (options.right_offset !== undefined) this.chart.wasm.set_right_offset(options.right_offset);
    this.chart.repaint();
  }
  options(): time_scale_options {
    return {
      bar_spacing: this.chart.wasm.bar_spacing(),
      right_offset: this.chart.wasm.right_offset(),
    };
  }
  get_visible_logical_range(): logical_range | null {
    const r = this.chart.wasm.visible_logical_range();
    return r.length === 2 ? { from: r[0]!, to: r[1]! } : null;
  }
  set_visible_logical_range(range: logical_range): void {
    this.chart.wasm.set_visible_logical_range(range.from, range.to);
    this.chart.repaint();
  }
  get_visible_range(): time_range | null {
    const r = this.chart.wasm.visible_time_range();
    return r.length === 2 ? { from: r[0]!, to: r[1]! } : null;
  }
  set_visible_range(range: time_range): void {
    this.chart.wasm.set_visible_time_range(range.from, range.to);
    this.chart.repaint();
  }
  subscribe_visible_logical_range_change(handler: visible_logical_range_handler): void {
    this.chart.subscribe_visible_logical_range_change(handler);
  }
  unsubscribe_visible_logical_range_change(handler: visible_logical_range_handler): void {
    this.chart.unsubscribe_visible_logical_range_change(handler);
  }
  subscribe_visible_time_range_change(handler: visible_time_range_handler): void {
    this.chart.subscribe_visible_time_range_change(handler);
  }
  unsubscribe_visible_time_range_change(handler: visible_time_range_handler): void {
    this.chart.unsubscribe_visible_time_range_change(handler);
  }
  time_to_coordinate(time: number): number | null {
    return undef_to_null(this.chart.wasm.time_to_coordinate(time));
  }
  coordinate_to_time(x: number): number | null {
    return undef_to_null(this.chart.wasm.coordinate_to_time(x));
  }
  logical_to_coordinate(logical: number): number | null {
    return undef_to_null(this.chart.wasm.logical_to_coordinate(logical));
  }
  coordinate_to_logical(x: number): number | null {
    return undef_to_null(this.chart.wasm.coordinate_to_logical(x));
  }
  time_to_index(time: number, find_nearest = false): number | null {
    const index = undef_to_null(this.chart.wasm.time_to_index(time, find_nearest));
    return index === null ? null : Number(index);
  }
  width(): number {
    return this.chart.wasm.time_scale_width();
  }
  height(): number {
    return this.chart.wasm.time_scale_height();
  }
}

class price_scale_impl implements price_scale_api {
  constructor(
    private readonly chart: chart_impl,
    private readonly pane: number,
    private readonly target: number,
  ) {}

  apply_options(options: deep_partial<price_scale_options>): void {
    if (options.mode !== undefined) {
      this.chart.wasm.set_price_scale_mode(this.pane, this.target, options.mode);
    }
    if (options.auto_scale !== undefined) {
      this.chart.wasm.set_price_scale_auto_scale(this.pane, this.target, options.auto_scale);
    }
    if (options.invert_scale !== undefined) {
      this.chart.wasm.set_price_scale_inverted(this.pane, this.target, options.invert_scale);
    }
    if (options.scale_margins !== undefined) {
      const current = this.options().scale_margins;
      this.chart.wasm.set_price_scale_margins(
        this.pane,
        this.target,
        options.scale_margins.top ?? current.top,
        options.scale_margins.bottom ?? current.bottom,
      );
    }
    this.chart.repaint();
  }

  options(): price_scale_options {
    const margins = this.chart.wasm.price_scale_margins(this.pane, this.target);
    return {
      mode: (this.chart.wasm.price_scale_mode(this.pane, this.target) ?? 0) as 0 | 1 | 2 | 3,
      auto_scale: this.chart.wasm.price_scale_auto_scale(this.pane, this.target) ?? false,
      invert_scale: this.chart.wasm.price_scale_inverted(this.pane, this.target) ?? false,
      scale_margins: {
        top: margins.length === 2 ? margins[0]! : 0,
        bottom: margins.length === 2 ? margins[1]! : 0,
      },
    };
  }

  width(): number {
    return this.chart.wasm.price_scale_width(this.pane, this.target);
  }

  set_visible_range(range: price_range): void {
    this.chart.wasm.set_price_scale_visible_range(this.pane, this.target, range.from, range.to);
    this.chart.repaint();
  }

  get_visible_range(): price_range | null {
    const range = this.chart.wasm.price_scale_visible_range(this.pane, this.target);
    return range.length === 2 ? { from: range[0]!, to: range[1]! } : null;
  }

  set_auto_scale(on: boolean): void {
    this.chart.wasm.set_price_scale_auto_scale(this.pane, this.target, on);
    this.chart.repaint();
  }
}

class pane_impl implements pane_api {
  constructor(private readonly chart: chart_impl, private readonly index: number) {}

  pane_index(): number {
    return this.index;
  }
  get_height(): number {
    return this.chart.wasm.pane_height(this.index);
  }
  set_height(height: number): void {
    this.chart.wasm.set_pane_height(this.index, height);
    this.chart.repaint();
  }
  get_stretch_factor(): number {
    return this.chart.wasm.pane_stretch(this.index);
  }
  set_stretch_factor(factor: number): void {
    this.chart.wasm.set_pane_stretch(this.index, factor);
    this.chart.repaint();
  }
}

class chart_impl implements chart_api {
  private next_extra_series = false;
  private readonly ts = new time_scale_impl(this);
  private observer: ResizeObserver | null = null;
  private detach_gestures: (() => void) | null = null;
  private removed = false;
  private readonly series_by_id = new Map<number, series_impl>();
  private readonly crosshair_subs = new Set<mouse_event_handler>();
  private readonly click_subs = new Set<mouse_event_handler>();
  private readonly dbl_click_subs = new Set<dbl_click_handler>();
  private readonly visible_logical_range_subs = new Set<visible_logical_range_handler>();
  private readonly visible_time_range_subs = new Set<visible_time_range_handler>();
  private last_visible_logical_range: logical_range | null;
  private last_visible_time_range: time_range | null;
  private readonly backend_runtime_id: number;
  private anim_frame: number | null = null;
  private readonly backend_loss_handler = (event: Event): void => {
    if ((event as CustomEvent<number>).detail !== this.backend_runtime_id || this.removed) return;
    // The wgpu callback may arrive from a promise microtask. Defer the repaint once more so the
    // callback stack is fully unwound before Rust drops GPU resources and paints the warm 2D pane.
    queueMicrotask(() => this.repaint());
  };

  constructor(
    readonly wasm: AionChart,
    private readonly container: HTMLElement,
    private readonly gpu_pane: HTMLCanvasElement,
    private readonly fallback_pane: HTMLCanvasElement,
    private readonly overlay: HTMLCanvasElement,
    auto_size: boolean,
  ) {
    this.backend_runtime_id = this.wasm.backend_runtime_id();
    window.addEventListener("aion-chart-backend-lost", this.backend_loss_handler);
    this.last_visible_logical_range = this.read_visible_logical_range();
    this.last_visible_time_range = this.read_visible_time_range();
    this.detach_gestures = install_gestures(this);
    if (auto_size) {
      this.wasm.enable_auto_resize(container);
    }
  }

  /** Repaint unless torn down. Named distinctly from the public `render` for internal use. */
  repaint(): void {
    if (!this.removed) {
      this.wasm.render();
      this.emit_visible_range_changes();
    }
  }

  private read_visible_logical_range(): logical_range | null {
    const r = this.wasm.visible_logical_range();
    return r.length === 2 ? { from: r[0]!, to: r[1]! } : null;
  }

  private read_visible_time_range(): time_range | null {
    const r = this.wasm.visible_time_range();
    return r.length === 2 ? { from: r[0]!, to: r[1]! } : null;
  }

  private emit_visible_range_changes(): void {
    const logical = this.read_visible_logical_range();
    const time = this.read_visible_time_range();
    const logical_changed = !same_logical_range(this.last_visible_logical_range, logical);
    const time_changed = !same_time_range(this.last_visible_time_range, time);
    this.last_visible_logical_range = logical;
    this.last_visible_time_range = time;

    if (logical_changed) {
      for (const handler of this.visible_logical_range_subs) {
        handler(logical ? { ...logical } : null);
      }
    }
    if (time_changed) {
      for (const handler of this.visible_time_range_subs) {
        handler(time ? { ...time } : null);
      }
    }
  }

  /** Start or stop the animation rAF loop to match whether any series wants the last-price pulse. */
  sync_animation(): void {
    if (this.removed) return;
    if (this.wasm.wants_animation()) {
      this.start_animation();
    } else {
      this.stop_animation();
    }
  }
  private start_animation(): void {
    if (this.anim_frame !== null || this.removed) return;
    const tick = () => {
      if (this.removed || !this.wasm.wants_animation()) {
        this.anim_frame = null;
        return;
      }
      this.wasm.set_animation_time(performance.now());
      this.wasm.render();
      this.anim_frame = requestAnimationFrame(tick);
    };
    this.anim_frame = requestAnimationFrame(tick);
  }
  private stop_animation(): void {
    if (this.anim_frame !== null) {
      cancelAnimationFrame(this.anim_frame);
      this.anim_frame = null;
    }
  }

  add_series(kind: series_kind, options?: Partial<series_options>): series_api {
    // Series 0 is created by the engine at construction; the first add_series adopts it so the
    // common "one chart, one series" path matches LWC (add_series returns the primary series).
    let id: number;
    if (!this.next_extra_series) {
      this.next_extra_series = true;
      this.wasm.set_series_type(KIND_TO_U8[kind]);
      id = 0;
    } else {
      id = this.wasm.add_series(KIND_TO_U8[kind]);
    }
    const series = new series_impl(id, kind, this);
    this.series_by_id.set(id, series);
    if (options) {
      series.apply_options(options);
    }
    return series;
  }

  private indicator_series(id: number, options?: Partial<series_options>): series_api {
    if (id === 0xffffffff) throw new Error("aion: invalid indicator configuration");
    const series = new series_impl(id, "line", this);
    this.series_by_id.set(id, series);
    if (options) series.apply_options(options);
    return series;
  }

  add_sma(source: series_api, period: number, options?: Partial<series_options>): series_api {
    return this.indicator_series(this.wasm.add_sma(source.id, Math.max(1, Math.floor(period))), options);
  }

  add_ema(source: series_api, period: number, options?: Partial<series_options>): series_api {
    return this.indicator_series(this.wasm.add_ema(source.id, Math.max(1, Math.floor(period))), options);
  }

  add_bollinger(source: series_api, period: number, deviation = 2, options?: Partial<series_options>): [series_api, series_api, series_api] {
    const ids = this.wasm.add_bollinger(source.id, Math.max(1, Math.floor(period)), deviation);
    if (ids.length !== 3) throw new Error("aion: invalid Bollinger configuration");
    return [this.indicator_series(ids[0]!, options), this.indicator_series(ids[1]!, options), this.indicator_series(ids[2]!, options)];
  }

  subscribe_crosshair_move(handler: mouse_event_handler): void {
    this.crosshair_subs.add(handler);
  }
  unsubscribe_crosshair_move(handler: mouse_event_handler): void {
    this.crosshair_subs.delete(handler);
  }
  subscribe_click(handler: mouse_event_handler): void {
    this.click_subs.add(handler);
  }
  unsubscribe_click(handler: mouse_event_handler): void {
    this.click_subs.delete(handler);
  }
  subscribe_dbl_click(handler: dbl_click_handler): void {
    this.dbl_click_subs.add(handler);
  }
  unsubscribe_dbl_click(handler: dbl_click_handler): void {
    this.dbl_click_subs.delete(handler);
  }
  subscribe_visible_logical_range_change(handler: visible_logical_range_handler): void {
    this.visible_logical_range_subs.add(handler);
  }
  unsubscribe_visible_logical_range_change(handler: visible_logical_range_handler): void {
    this.visible_logical_range_subs.delete(handler);
  }
  subscribe_visible_time_range_change(handler: visible_time_range_handler): void {
    this.visible_time_range_subs.add(handler);
  }
  unsubscribe_visible_time_range_change(handler: visible_time_range_handler): void {
    this.visible_time_range_subs.delete(handler);
  }

  /** Build event params for a cursor at (x, y) in pane CSS px. */
  private build_params(x: number, y: number): mouse_event_params {
    const time = undef_to_null(this.wasm.coordinate_to_time(x));
    const logical = undef_to_null(this.wasm.coordinate_to_logical(x));
    const flat = this.wasm.hover_data(x); // groups of [id, o, h, l, c]
    const series_data = new Map<series_api, ohlc_data | single_value_data>();
    const t = time ?? 0;
    for (let i = 0; i + 4 < flat.length; i += 5) {
      const s = this.series_by_id.get(flat[i]!);
      if (!s) continue;
      const [o, h, l, c] = [flat[i + 1]!, flat[i + 2]!, flat[i + 3]!, flat[i + 4]!];
      series_data.set(
        s,
        s.kind === "candlestick" || s.kind === "bar"
          ? { time: t, open: o, high: h, low: l, close: c }
          : { time: t, value: c },
      );
    }
    return { time, logical, point: { x, y }, series_data };
  }

  /** Emit a crosshair-move event (called by the gesture recognizer). */
  emit_crosshair(x: number, y: number): void {
    if (this.crosshair_subs.size === 0) return;
    const params = this.build_params(x, y);
    for (const h of this.crosshair_subs) h(params);
  }
  /** Emit the "cursor left the chart" crosshair event (empty params). */
  emit_crosshair_left(): void {
    if (this.crosshair_subs.size === 0) return;
    const params: mouse_event_params = { time: null, logical: null, point: null, series_data: new Map() };
    for (const h of this.crosshair_subs) h(params);
  }
  /** Emit a click event (called by the gesture recognizer). */
  emit_click(x: number, y: number): void {
    if (this.click_subs.size === 0) return;
    const params = this.build_params(x, y);
    for (const h of this.click_subs) h(params);
  }

  emit_dbl_click(x: number, y: number): void {
    if (this.dbl_click_subs.size === 0) return;
    const params = this.build_params(x, y);
    for (const h of this.dbl_click_subs) h(params);
  }

  apply_options(options: deep_partial<chart_options>): void {
    this.wasm.apply_options(JSON.stringify(options));
    this.repaint();
  }

  options(): unknown {
    return JSON.parse(this.wasm.options_json());
  }

  backend(): "webgpu" | "canvas2d" {
    return this.wasm.backend_kind() as "webgpu" | "canvas2d";
  }

  time_scale(): time_scale_api {
    return this.ts;
  }

  price_scale(price_scale_id: "left" | "right" | "" = "right", pane_index = 0): price_scale_api {
    const target = price_scale_id === "left" ? 1 : price_scale_id === "" ? 2 : 0;
    return new price_scale_impl(this, pane_index, target);
  }

  panes(): pane_api[] {
    const n = this.wasm.pane_count();
    const out: pane_api[] = [];
    for (let i = 0; i < n; i++) {
      out.push(new pane_impl(this, i));
    }
    return out;
  }

  price_to_coordinate(price: number): number | null {
    return undef_to_null(this.wasm.price_to_coordinate(price));
  }
  coordinate_to_price(y: number): number | null {
    return undef_to_null(this.wasm.coordinate_to_price(y));
  }

  resize(width: number, height: number, dpr?: number): void {
    this.wasm.resize(width, height, dpr ?? window.devicePixelRatio ?? 1);
    this.repaint();
  }

  render(): void {
    this.repaint();
  }

  take_screenshot(): HTMLCanvasElement {
    // Browser WebGPU canvases are presentable but are not synchronously readable through
    // CanvasRenderingContext2D.drawImage (Chromium returns transparent pixels). Repaint the current
    // engine frame, then execute that same retained frame through the already-warm Canvas2D pane.
    // This keeps the LWC-style synchronous API deterministic without duplicating chart state.
    this.repaint();
    this.wasm.render_canvas2d_snapshot();
    const output = document.createElement("canvas");
    output.width = this.overlay.width;
    output.height = this.overlay.height;
    const ctx = output.getContext("2d");
    if (ctx === null) throw new Error("aion: screenshot Canvas2D context is unavailable");
    ctx.drawImage(this.fallback_pane, 0, 0);
    ctx.drawImage(this.overlay, 0, 0);
    return output;
  }

  overlay_el(): HTMLCanvasElement {
    return this.overlay;
  }

  remove(): void {
    if (this.removed) return;
    this.removed = true;
    this.stop_animation();
    window.removeEventListener("aion-chart-backend-lost", this.backend_loss_handler);
    this.detach_gestures?.();
    this.observer?.disconnect();
    this.gpu_pane.remove();
    this.fallback_pane.remove();
    this.overlay.remove();
  }
}

// ---------------------------------------------------------------------------------------------
// Gesture recognizer (ported from the demo; the engine exposes the primitives)
// ---------------------------------------------------------------------------------------------

function install_gestures(chart: chart_impl): () => void {
  const overlay = chart.overlay_el();
  const wasm = chart.wasm;
  const pointers = new Map<number, { x: number; y: number }>();
  let dragging = false;
  let pinch_dist = 0;
  // separator drag state (roadmap Phase B1): index of the separator being dragged + last Y
  let sep_drag: { index: number; last_y: number } | null = null;
  const SEP_HIT = 4; // css px hit tolerance around a pane boundary

  const local_xy = (e: { clientX: number; clientY: number }) => {
    const r = overlay.getBoundingClientRect();
    return { x: e.clientX - r.left - wasm.pane_left(), y: e.clientY - r.top };
  };

  /** Index of the separator within SEP_HIT px of css-y `y`, or -1. */
  const separator_at = (y: number): number => {
    const ys = wasm.pane_separator_ys();
    for (let i = 0; i < ys.length; i++) {
      if (Math.abs(y - ys[i]!) <= SEP_HIT) return i;
    }
    return -1;
  };

  const on_wheel = (e: WheelEvent) => {
    e.preventDefault();
    const delta_y = -(e.deltaY / 100);
    if (delta_y !== 0) {
      const zoom_scale = Math.sign(delta_y) * Math.min(1, Math.abs(delta_y));
      wasm.zoom(e.offsetX - wasm.pane_left(), zoom_scale);
      chart.repaint();
    }
  };
  const on_down = (e: PointerEvent) => {
    try {
      overlay.setPointerCapture(e.pointerId);
    } catch {
      // ignore (e.g. synthetic events with no active pointer)
    }
    const p = local_xy(e);
    pointers.set(e.pointerId, p);
    // start a separator drag instead of a pan when pressing on a pane boundary
    if (pointers.size === 1) {
      const si = separator_at(p.y);
      if (si >= 0) {
        sep_drag = { index: si, last_y: p.y };
        return;
      }
    }
    if (pointers.size === 1) {
      dragging = true;
      wasm.scroll_start(p.x);
    } else if (pointers.size === 2) {
      dragging = false;
      wasm.scroll_end();
      const [a, b] = [...pointers.values()];
      pinch_dist = Math.hypot(a!.x - b!.x, a!.y - b!.y);
    }
  };
  const on_move = (e: PointerEvent) => {
    const p = local_xy(e);
    // active separator drag: resize the two adjacent panes
    if (sep_drag !== null) {
      const dy = p.y - sep_drag.last_y;
      sep_drag.last_y = p.y;
      wasm.drag_pane_separator(sep_drag.index, dy);
      chart.repaint();
      return;
    }
    // hover cursor feedback over a separator (no button pressed)
    if (pointers.size === 0) {
      overlay.style.cursor = separator_at(p.y) >= 0 ? "row-resize" : "crosshair";
    }
    if (pointers.has(e.pointerId)) pointers.set(e.pointerId, p);
    if (pointers.size >= 2) {
      const [a, b] = [...pointers.values()];
      const dist = Math.hypot(a!.x - b!.x, a!.y - b!.y);
      const mid = (a!.x + b!.x) / 2;
      if (pinch_dist > 0 && dist > 0) {
        const zoom_scale = Math.max(-1, Math.min(1, (dist - pinch_dist) / 40));
        if (zoom_scale !== 0) wasm.zoom(mid, zoom_scale);
      }
      pinch_dist = dist;
      chart.repaint();
      return;
    }
    if (dragging) wasm.scroll_move(p.x);
    wasm.set_crosshair(p.x, p.y);
    chart.repaint();
    chart.emit_crosshair(p.x, p.y);
  };
  const end_pointer = (e: PointerEvent) => {
    pointers.delete(e.pointerId);
    if (sep_drag !== null && pointers.size === 0) {
      sep_drag = null;
      return;
    }
    if (pointers.size < 2) pinch_dist = 0;
    if (pointers.size === 0) {
      if (dragging) {
        dragging = false;
        wasm.scroll_end();
      }
      wasm.clear_crosshair();
      chart.repaint();
      chart.emit_crosshair_left();
    }
  };
  const on_dblclick = (e: MouseEvent) => {
    const p = local_xy(e);
    chart.emit_dbl_click(p.x, p.y);
    wasm.fit_content();
    chart.repaint();
  };
  const on_click = (e: MouseEvent) => {
    const p = local_xy(e);
    chart.emit_click(p.x, p.y);
  };
  const on_leave = (e: PointerEvent) => {
    if (e.pointerType === "mouse") end_pointer(e);
  };

  overlay.addEventListener("wheel", on_wheel, { passive: false });
  overlay.addEventListener("pointerdown", on_down);
  overlay.addEventListener("pointermove", on_move);
  overlay.addEventListener("pointerup", end_pointer);
  overlay.addEventListener("pointercancel", end_pointer);
  overlay.addEventListener("pointerleave", on_leave);
  overlay.addEventListener("dblclick", on_dblclick);
  overlay.addEventListener("click", on_click);

  return () => {
    overlay.removeEventListener("wheel", on_wheel);
    overlay.removeEventListener("pointerdown", on_down);
    overlay.removeEventListener("pointermove", on_move);
    overlay.removeEventListener("pointerup", end_pointer);
    overlay.removeEventListener("pointercancel", end_pointer);
    overlay.removeEventListener("pointerleave", on_leave);
    overlay.removeEventListener("dblclick", on_dblclick);
    overlay.removeEventListener("click", on_click);
  };
}

// ---------------------------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------------------------

/**
 * Create a chart inside `container`. Resolves once the rendering backend is ready and the first
 * frame is drawn. Mirrors lightweight-charts' `createChart`, but async (backend acquisition).
 */
export async function create_chart(
  container: HTMLElement,
  options?: deep_partial<chart_options>,
): Promise<chart_api> {
  await ensure_init();

  // Three stacked, absolutely-positioned canvases fill the container: dedicated WebGPU and
  // Canvas2D panes below the transparent axis/input overlay. A canvas cannot change context type,
  // so keeping the fallback pane warm is what makes device-loss failover possible without
  // recreating the chart or moving state out of the headless engine.
  if (getComputedStyle(container).position === "static") {
    container.style.position = "relative";
  }
  const gpu_pane = document.createElement("canvas");
  const fallback_pane = document.createElement("canvas");
  const overlay = document.createElement("canvas");
  for (const c of [gpu_pane, fallback_pane, overlay]) {
    c.style.position = "absolute";
    c.style.inset = "0";
    c.style.width = "100%";
    c.style.height = "100%";
    c.style.display = "block";
    (c.style as CSSStyleDeclaration & { touchAction: string }).touchAction = "none";
  }
  overlay.style.cursor = "crosshair";
  container.appendChild(gpu_pane);
  container.appendChild(fallback_pane);
  container.appendChild(overlay);

  const rect = container.getBoundingClientRect();
  const css_w = Math.max(rect.width, 1);
  const css_h = Math.max(rect.height, 1);
  const dpr = window.devicePixelRatio || 1;
  // Bootstrap the bitmap size so either pane backend configures; auto-resize (if enabled) or a
  // manual resize() will correct it.
  for (const c of [gpu_pane, fallback_pane, overlay]) {
    c.width = Math.max(1, Math.round(css_w * dpr));
    c.height = Math.max(1, Math.round(css_h * dpr));
  }

  const simulate_adapter_failure = (
    options as (deep_partial<chart_options> & {
      __simulate_webgpu_adapter_failure?: boolean;
      __force_webgpu_fallback_adapter?: boolean;
    }) | undefined
  )?.__simulate_webgpu_adapter_failure === true;
  const force_fallback_adapter = (
    options as (deep_partial<chart_options> & { __force_webgpu_fallback_adapter?: boolean }) | undefined
  )?.__force_webgpu_fallback_adapter === true;
  const wasm = await wasm_create_chart(
    gpu_pane,
    fallback_pane,
    overlay,
    css_w,
    css_h,
    dpr,
    options?.backend === "canvas2d",
    simulate_adapter_failure,
    force_fallback_adapter,
  );
  if (options) {
    wasm.apply_options(JSON.stringify(options));
  }
  const auto_size = options?.autoSize === true;
  const chart = new chart_impl(wasm, container, gpu_pane, fallback_pane, overlay, auto_size);
  chart.render();
  return chart;
}
