/**
 * @aion/charts — public API (snake_case; semantics mirror lightweight-charts v5).
 *
 * A thin, typed façade over the `aion_wasm` engine. It owns the browser-side concerns that the
 * engine deliberately leaves out: creating the two stacked canvases (WebGPU/Canvas2D pane +
 * Canvas2D axis overlay), the input-gesture recognizer, typed-array packing of data at the
 * boundary, and the chart/series/time-scale handle objects. All model, layout, and rendering math
 * lives in Rust.
 *
 * WebGPU device acquisition is async, so `create_chart` returns a Promise — the one deliberate
 * divergence from LWC's synchronous `createChart`.
 */

// The wasm glue is generated by `wasm-pack` into ../pkg (see `npm run build:wasm`). esbuild inlines
// it when bundling; the .wasm is fetched at runtime relative to the output bundle.
// @ts-ignore -- pkg is a build artifact, present after build:wasm
import { create_chart as wasm_create_chart } from "../pkg/aion_wasm.js";

export * from "./types.js";
export * from "./theme.js";
import { chart_impl } from "./impl.js";
import { ensure_init } from "./impl.js";
import { theme_options } from "./theme.js";
import type { chart_api, chart_options, deep_partial, localization_options } from "./types.js";

// ---------------------------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------------------------

/**
 * Create a chart inside `container`. Resolves once the rendering backend is ready and the first
 * frame is drawn. Mirrors lightweight-charts' `createChart`, but async (backend acquisition).
 */
export async function create_chart(
  container: HTMLElement,
  options?: deep_partial<chart_options>,
): Promise<chart_api> {
  await ensure_init();

  // Three stacked, absolutely-positioned canvases fill the container: dedicated WebGPU and
  // Canvas2D panes below the transparent axis/input overlay. A canvas cannot change context type,
  // so keeping the fallback pane warm is what makes device-loss failover possible without
  // recreating the chart or moving state out of the headless engine.
  if (getComputedStyle(container).position === "static") {
    container.style.position = "relative";
  }
  const gpu_pane = document.createElement("canvas");
  const fallback_pane = document.createElement("canvas");
  const overlay = document.createElement("canvas");
  for (const c of [gpu_pane, fallback_pane, overlay]) {
    c.style.position = "absolute";
    c.style.inset = "0";
    c.style.width = "100%";
    c.style.height = "100%";
    c.style.display = "block";
    (c.style as CSSStyleDeclaration & { touchAction: string }).touchAction = "none";
  }
  overlay.style.cursor = "crosshair";
  container.appendChild(gpu_pane);
  container.appendChild(fallback_pane);
  container.appendChild(overlay);

  const rect = container.getBoundingClientRect();
  const css_w = Math.max(rect.width, 1);
  const css_h = Math.max(rect.height, 1);
  const dpr = window.devicePixelRatio || 1;
  // Bootstrap the bitmap size so either pane backend configures; auto-resize (if enabled) or a
  // manual resize() will correct it.
  for (const c of [gpu_pane, fallback_pane, overlay]) {
    c.width = Math.max(1, Math.round(css_w * dpr));
    c.height = Math.max(1, Math.round(css_h * dpr));
  }

  const simulate_adapter_failure = (
    options as (deep_partial<chart_options> & {
      __simulate_webgpu_adapter_failure?: boolean;
      __force_webgpu_fallback_adapter?: boolean;
    }) | undefined
  )?.__simulate_webgpu_adapter_failure === true;
  const force_fallback_adapter = (
    options as (deep_partial<chart_options> & { __force_webgpu_fallback_adapter?: boolean }) | undefined
  )?.__force_webgpu_fallback_adapter === true;
  const wasm = await wasm_create_chart(
    gpu_pane,
    fallback_pane,
    overlay,
    css_w,
    css_h,
    dpr,
    options?.backend === "canvas2d",
    simulate_adapter_failure,
    force_fallback_adapter,
  );
  // Default style settings first (theme.ts), explicit options second — the engine deep-merges
  // successive patches, so caller options always win over the theme palette. `theme`,
  // `handle_scroll`, and `handle_scale` are package-level keys and are not forwarded to the
  // engine's options store (gestures live entirely in TS).
  const { theme, handle_scroll, handle_scale, kinetic_scroll, localization, ...engine_options } =
    options ?? {};
  wasm.apply_options(JSON.stringify(theme_options(theme ?? "light")));
  if (Object.keys(engine_options).length > 0) {
    wasm.apply_options(JSON.stringify(engine_options));
  }
  const auto_size = options?.autoSize === true;
  const chart = new chart_impl(wasm, container, gpu_pane, fallback_pane, overlay, auto_size);
  if (handle_scroll !== undefined || handle_scale !== undefined || kinetic_scroll !== undefined) {
    chart.apply_gesture_options(handle_scroll, handle_scale, kinetic_scroll);
  }
  if (localization !== undefined) {
    // deep_partial recurses into the callback signatures; the fields are already optional, so the
    // concrete localization_options shape is what apply_localization expects.
    chart.apply_localization(localization as localization_options);
  }
  chart.render();
  return chart;
}
